server:
  ipAddr: 127.0.0.1
  port: 8091
  ssl: false

logger:
  path: ./
  level: warn
  period: 1d

db:
  database: lucky1
  host: 127.0.0.1
  dialect: mysql
  port: 3306
  username: root
  password: ''
